### ISSUE TITLE
 请问：ERROR：Service name已存在这样的报错如何解决呢？

### ISSUE THREAD

**Issue by CYDXDianXian** [assassingyk/bandori-predict#3]
我研究了一夜了，实在没找到办法，迫不得已来请大佬帮帮忙。我已经检查过没有重复的Service名称，至于有没有可能重复加载Service我也无从得知，还请大佬帮忙看看是什么情况，不胜感激！
保存信息如下：
```
[2021-08-13 23:09:12,078 nonebot] ERROR: Failed to import "hoshino.modules.bandori_predict.getData", error: Service name "bangdream-predict" already exist!
[2021-08-13 23:09:12,079 nonebot] ERROR: Service name "bangdream-predict" already exist!
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/qqbot/HoshinoBot/hoshino/modules/bandori_predict/__init__.py", line 28, in <module>
    sv = Service('bangdream-predict', help_=sv_help)
  File "/home/ubuntu/qqbot/HoshinoBot/hoshino/service.py", line 128, in __init__
    assert self.name not in _loaded_services, f'Service name "{self.name}" already exist!'
AssertionError: Service name "bangdream-predict" already exist!
```

**Comment by assassingyk** [comment]
啊，应该是import那个imgbasepath那边出了问题，昨天直接在git上改的没调试）

**Comment by assassingyk** [comment]
把所有配置项从init里分离出去应该可以解决，你等我修一下）

**Comment by CYDXDianXian** [comment]
> 把所有配置项从init里分离出去应该可以解决，你等我修一下）

哇！感谢大佬帮忙了！Orz

**Comment by assassingyk** [comment]
好了，你再试试）

**Comment by CYDXDianXian** [comment]
> 好了，你再试试）

谢谢！试了，已经没问题了！赞！
